#!/usr/bin/env ruby

# Prepend version to every commit message
msgfile = ARGV[0]
regex1 = /\d+\.\d+\.\d+:\s(.*)/
regex2 = /\s*release:\s*(\d+\.\d+\.\d+)/
File.open('spec.yml', 'r') do |f|
  ver = f.readlines.find{|x| x[regex2, 1]}[regex2, 1]
  msg = File.read(msgfile)
  msg = msg[regex1, 1] if msg[regex1, 1]
  File.write(msgfile, "#{ver}: #{msg}")
end

# vim: ft=ruby:ts=2:sw=2:sts=2
