#!/usr/bin/env ruby
#MIT License
#Copyright (c) 2017-2018 phR0ze
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

# Prepend version to every commit message
# Get version from the build.yml spec
msgfile = ARGV[0]
regex1 = /\d+\.\d+\.\d+:\s(.*)/
regex2 = /\s*release:\s*(\d+\.\d+\.\d+)/
File.open('specs/build.yml', 'r') do |f|
  ver = f.readlines.find{|x| x[regex2, 1]}[regex2, 1]
  msg = File.read(msgfile)
  msg = msg[regex1, 1] if msg[regex1, 1]
  File.write(msgfile, "#{ver}: #{msg}")
end

# vim: ft=ruby:ts=2:sw=2:sts=2
