#!/usr/bin/env ruby

# Increment SemVer formatted versions
# Params:
# +files+:: files to increment version for
# +regex+:: capture pattern for version match
# +override+:: value to use for version if set
def increment_version(files, regex, override:nil)
  result = nil
  files = [files] if files.is_a?(String)

  files.each{|filename|
    begin
      lines = nil
      File.open(filename, 'r+') do |f|
        lines = f.readlines
        lines.each{|line|

          # Increment version
          if ver = line[regex, 1]
            new_ver = nil
            if not override
              new_ver = ver.strip.split('.')
              new_ver[2] = new_ver[2].to_i + 1
              new_ver = new_ver * '.'
            else
              new_ver = override
            end

            # Modify the original line
            line.gsub!(ver, new_ver)
            result = new_ver
          end
        }

        # Save the changes back to the file
        f.seek(0)
        f.truncate(0)
        f.puts(lines)
      end

      # Now add the modified file to the git commit
      `git add #{filename}`
    rescue
      # Revert back to the original incase of failure
      File.open(filename, 'w'){|f| f.puts(lines)} if lines
      raise
    end
  }

  return result
end

# Auto-increment versions
ver = increment_version('spec.yml', /\s*release:\s*(\d+\.\d+\.\d+)/, override:nil)
puts("Version: #{ver}")

# vim: ft=ruby:ts=2:sw=2:sts=2
