#!/usr/bin/env ruby
#MIT License
#Copyright (c) 2017-2018 phR0ze
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

require 'fileutils'             # advanced file utils: FileUtils
require 'mkmf'                  # system utils: find_executable
require 'open-uri'              # easily read HTTP
require 'ostruct'               # OpenStruct
require 'open3'                 # Better system commands
require 'rubygems/package'      # tar
require 'yaml'                  # YAML

require_relative 'lib/core'     # ERB Handlers for different types
require_relative 'lib/config'   # Programatic file editor and command runner
require_relative 'lib/cmds'     # optparse wrapper for commands
require_relative 'lib/sys'      # System helpers

# Gems that should already be installed
begin
  require 'colorize'            # color output: colorize
  require 'filesize'            # human readable file sizes: Filesize
  require 'net/ssh'             # ssh integration: Net::SSH
  require 'net/scp'             # scp integration: Net::SCP
rescue Exception => e
  mod = e.message.split(' ').last.sub('/', '-')
  !puts("Error: install missing package with 'sudo pacman -S ruby-#{mod}'") and exit
end

class Reduce

  def initialize
    @type = OpenStruct.new({
      img: 'img',
      iso: 'iso',
      box: 'box',
      tgz: 'tgz',
      sqfs: 'sqfs'
    })
    @k = OpenStruct.new({
      all: 'all',
      apps: 'apps',
      base: 'base',
      build: 'build',
      configs: 'configs',
      command: 'command',
      cpus: 'cpus',
      conflict: 'conflict',
      container: 'container',
      desc: 'desc',
      deployment: 'deployment',
      deployments: 'deployments',
      docker: 'docker',
      entry: 'entry',
      force: 'force',
      groups: 'groups',
      i686: 'i686',
      ignore: 'ignore',
      install: 'install',
      kernel: 'kernel',
      machine: 'machine',
      mirrors: 'mirrors',
      multilib: 'multilib',
      name: 'name',
      off: 'off',
      packages: 'packages',
      params: 'params',
      pgp_key: 'pgp_key',
      ram: 'ram',
      source: 'source',
      type: 'type',
      vagrant: 'vagrant',
      vars: 'vars',
      vram: 'vram',
      v3d: 'v3d',
      x86_64: 'x86_64',
    })

    @rootpath = File.dirname(File.expand_path(__FILE__))
    @user = Process.uid.zero? ? Etc.getpwuid(ENV['SUDO_UID'].to_i).name : ENV['USER']
    @sudoinv = Process.uid.zero? ? "sudo -Hu #{@user} " : ''
    @runuser = "runuser #{@user} -c"

    # Load base profile
    @profile = {@k.deployments => {}, @k.apps => {}}
    @vars = OpenStruct.new
    load_profile('_base')

    # Set proxy vars
    @proxyenv = {
      'ftp_proxy' => ENV['ftp_proxy'],
      'http_proxy' => ENV['http_proxy'],
      'https_proxy' => ENV['https_proxy'],
      'no_proxy' => ENV['no_proxy']
    }
    @proxy = ENV['http_proxy']
    @proxy_export = @proxy ? (@proxyenv.map{|k,v| "export #{k}=#{v}"} * ';') + ";" : nil
    @vars.proxy = @proxy

    # Set paths
    @outpath = File.join(@rootpath, 'temp')
    @workpath = File.join(@outpath, 'work')
    @pacman_path = File.join(@outpath, 'pacman')
    @tmp_dir = File.join(@workpath, 'tmp')
    @isopath = File.join(@workpath, '_iso_')
    @deployments_src = File.join(@rootpath, 'source')
    @deployments_work = File.join(@workpath, 'deployments')
    @vagrantpath = File.join(@rootpath, 'vagrant')

    @motd_path = File.join(@deployments_src, 'base/etc/motd')
    @pacman_sync = File.join(@pacman_path, 'sync')
    @pacman_conf = File.join(@pacman_path, 'pacman.conf')
    @pacman_src_conf = File.join(@deployments_src, 'base/etc/pacman.conf')
    @pacman_src_mirrors = File.join(@deployments_src, 'base/etc/pacman.d/*.mirrorlist')

    @boot_dst = File.join(@isopath, 'boot')
    @deployment_images_dst = File.join(@isopath, 'images')
    @grub_iso_dst = File.join(@boot_dst, 'grub')
    @grub_iso_src = File.join(@rootpath, 'boot/grub_iso')
    @grub_iso_work = File.join(@workpath, 'boot/grub_iso')

    @kernel_path = @boot_dst
    @kernel_prefix = 'vmlinuz'
    @memtest_image = File.join(@boot_dst, 'memtest')
    @ucode_image = File.join(@boot_dst, 'intel-ucode')

    @initramfs_path = @boot_dst
    @initramfs_prefix = 'initramfs'
    @initramfs_src = File.join(@rootpath, 'boot/initramfs')
    @initramfs_work = File.join(@workpath, 'boot/initramfs')

    @packer_src = File.join(@rootpath, 'packer')
    @packer_work = File.join(@workpath, 'packer')

    @imagepaths = [
      File.join(@outpath, 'images'),
      @deployment_images_dst,
      File.expand_path('~').include?('root') ? "/home/#{@user}/Downloads/images" :
        File.join(File.expand_path('~'), 'Downloads', 'images')]
  end

  # Load and return the given profile
  # @param profile [String] name of the profile to load
  def load_profile(profile)
    profile_path = File.join(@rootpath, "profiles/#{profile}.yml")

    begin
      profile = YAML.load_file(profile_path)

      # Load vars and validate base vars
      profile[@k.vars].each{|k,v| @vars[k.to_sym] = v} if profile[@k.vars]

      if profile[@k.base]
        load_profile(profile[@k.base])
      else
        validate = ->(name, pred){
          !puts("Error: '#{name}' is invalid in '#{profile}'".colorize(:red)) and exit unless pred
        }
        validate.call('arch', [@k.i686, @k.x86_64].include?(@vars.arch))
        validate.call('release', @vars.release)
        validate.call('distro', @vars.distro)
        validate.call('language', @vars.language)
        validate.call('character_set', @vars.character_set)
        validate.call('timezone', @vars.timezone)
        validate.call('country', @vars.country)
        validate.call('color_light', @vars.color_light)
        validate.call('color_dark', @vars.color_dark)
        validate.call('gfxmode', @vars.gfxmode)
        validate.call('grub_iso_theme', @vars.grub_iso_theme)

        # Configure variables
        @vars.label = "#{@vars.distro.upcase}_#{@vars.release.gsub('.', '')}"
      end

      # Load and merge apps and deployments
      @profile[@k.apps].merge!(profile[@k.apps]) if profile[@k.apps]
      @profile[@k.deployments].merge!(profile[@k.deployments]) if profile[@k.deployments]

      # Set deployment and group variables as needed
      @profile[@k.deployments].each{|k,v|
        @vars["#{k}_deployment"] = get_deployments(k) * ',' if v[@k.type] == @k.machine }
      @profile[@k.deployments].each{|k,v|
        @vars["#{k}_groups"] = get_deployments(k).map{|x|
          @profile[@k.deployments][x][@k.groups] if @profile[@k.deployments][x][@k.groups]}.compact.uniq * ','
      }

    rescue Exception => e
      puts("Error: invalid yaml in '#{profile_path}'".colorize(:red))
      puts(e.to_s.colorize(:red))
      raise
    end
  end

  # Create directory structure for project
  def create_dir_structure
    uid, gid = Sys.drop_privileges

    puts("Creating directory structure")
    FileUtils.mkdir_p(@pacman_path)
    FileUtils.mkdir_p(@pacman_sync)
    FileUtils.mkdir_p(@workpath)
    FileUtils.mkdir_p(@tmp_dir)
    FileUtils.mkdir_p(@isopath)
    FileUtils.mkdir_p(@deployment_images_dst)
    FileUtils.mkdir_p(@boot_dst)

    FileUtils.mkdir_p(@grub_iso_dst)
    FileUtils.mkdir_p(@grub_iso_work)
    FileUtils.mkdir_p(@deployments_work)
    FileUtils.mkdir_p(@initramfs_work)

    FileUtils.mkdir_p(@imagepaths.first)
    FileUtils.mkdir_p(@packer_work)
    FileUtils.mkdir_p(@vagrantpath)

    Sys.raise_privileges(uid, gid)
  end

  # Print out distro information
  def info
    load_profile('_base')

    # Scrape Arch Linux kernel package
    opts = { ssl_verify_mode: 0, proxy:@proxy }
    page = open("https://www.archlinux.org/packages/core/x86_64/linux", opts).read
    @vars.kernel = page[/<title>(.*?)<\/title>/, 1][/.*linux (.*) \(x86_64\)/, 1]

    puts("Distro: #{@vars.distro}".colorize(:green))
    puts("Release: #{@vars.release}".colorize(:green))
    puts("Arch: #{@vars.arch}".colorize(:green))
    puts("Kernel: #{@vars.kernel}".colorize(:green))
    puts("Source path: #{@rootpath}".colorize(:green))
    puts("Output path: #{@outpath}".colorize(:green))
    puts("Proxy: #{@proxyenv['http_proxy']}".colorize(:green)) if @proxy
  end

  # List components as directed
  # @param boxes [bool] list all boxes
  # @param isos [bool] list all isos
  # @param images [bool] list all docker images
  # @param all [bool] list all components
  def list(boxes:nil, isos:nil, images:nil, all:nil)
    all = all || ![boxes, isos, images].any?

    # Formatting block for images
    putimages = ->(type, live, name){
      puts("#{name.ljust(100, ' ')}Size:".colorize(:cyan))
      getimages(type, live:live).each{|k,v|
        size = v.to_s.count("a-zA-Z").zero? ? Filesize.from("#{v} B").to_s('MiB') : v
        puts("#{k.ljust(100, ' ')}#{size}")
      }
      puts
    }

    putimages.call(@type.box, false, 'Boxes:') if boxes or all
    putimages.call(@type.iso, false, 'ISOs:') if isos or all
    putimages.call(@type.img, false, 'Boot Images:') if isos or all
    putimages.call(@type.sqfs, false, 'Machine Images:') if isos or all
    putimages.call(@type.tgz, false, 'Container Images:') if images or all
    putimages.call(@type.tgz, true, 'Container Deployed Images:') if images or all
  end

  # Clean components as directed
  # @param pacman [bool] clean pacman repos
  # @param pacman_all [bool] clean pacman repos and cache
  # @param initramfs [bool] clean initramfs component
  # @param multiboot [bool] clean multiboot components
  # @param deployments [bool] clean given deployments
  # @param iso [bool] clean iso image
  # @param vms [bool] clean vms
  # @param all [bool] clean all components
  # @param isofull [bool] clean iso image including all machine deployments
  def clean(pacman:nil, pacman_all:nil, initramfs:nil, multiboot:nil, deployments:nil, iso:nil, vms:nil, all:nil, isofull:nil)
    !puts("Error: no clean options specified".colorize(:red)) and
      exit unless [pacman, pacman_all, initramfs, multiboot, deployments, iso, vms, all, isofull].any?
    !puts("Error: must be executed as root".colorize(:red)) and
      exit unless Process.uid.zero?

    # Clean all
    if all
      puts("Cleaning all...".colorize(:cyan))
      puts("Deleting #{@workpath}".colorize(:red)) if File.exist?(@workpath)
      Sys.rm_rf(@workpath)
    end

    # Clean initramfs component
    if !all and (initramfs or isofull)
      puts("Cleaning initamfs...".colorize(:cyan))
      puts("Deleting #{@initramfs_work}".colorize(:red)) if File.exist?(@initramfs_work)
      Sys.rm_rf(@initramfs_work)
      Dir[File.join(@initramfs_path, "#{@initramfs_prefix}*")].each{|x|
        puts("Deleting #{x}".colorize(:red))
        Sys.rm_rf(x)
      }
    end

    # Clean grub iso components
    if !all and (multiboot or deployments or isofull)
      puts("Cleaning multiboot...".colorize(:cyan))
      [@grub_iso_work, @grub_iso_dst].each{|x|
        puts("Deleting #{x}".colorize(:red)) if File.exist?(x)
        Sys.rm_rf(x)
      }
      (Dir[File.join(@kernel_path, "#{@kernel_prefix}*")] + ["#{@ucode_image}.img",
        "#{@ucode_image}.LICENSE", @memtest_image, "#{@memtest_image}.LICENSE"]).each{|x|
        puts("Deleting #{x}".colorize(:red)) if File.exist?(x)
        File.delete(x) if File.exist?(x)
      }
    end

    # Clean given deployments
    if !all and Dir.exist?(@deployments_work) and (deployments || isofull)
      (deployments || ((all || isofull) ? Dir.children(@deployments_work) : nil)).each{|deployment|
        puts("Cleaning deployment '#{deployment}'...".colorize(:cyan))
        path = File.join(@deployments_work, deployment)
        puts("Deleting #{path}".colorize(:red)) if File.exist?(path)
        Sys.rm_rf(path)
        @imagepaths[0..1].each{|path|
          Dir[File.join(path, "#{deployment}*")].each{|x|
            puts("Deleting #{x}".colorize(:red))
            File.delete(x)}
        }
        evalimages!(@type.tgz, deployment:deployment, live:true, force:true)
      }
    end

    # Clean pacman
    if pacman or pacman_all or all
      puts("Cleaning pacman repos...".colorize(:cyan))
      puts("Cleaning pacman cache...".colorize(:cyan)) if pacman_all
      if pacman_all
        puts("Deleting #{@pacman_path}".colorize(:red)) if Dir.exist?(@pacman_path)
        Sys.rm_rf(@pacman_path)
      elsif pacman
        puts("Deleting repo files".colorize(:red))
        Sys.rm_rf(File.join(@pacman_path, 'sync'))
        Sys.rm_rf(File.join(@pacman_path, 'gnupg'))
        Dir[File.join(@pacman_path, '*.mirrorlist')].each{|f| File.delete(f) }
        Dir[File.join(@pacman_path, '*.conf')].each{|f| File.delete(f) }
        Dir[File.join(@pacman_path, '*.log')].each{|f| File.delete(f) }
      end
    end

    # Clean iso path
    if !all and isofull
      puts("Cleaning iso path...".colorize(:cyan))
      puts("Deleting #{@isopath}".colorize(:red)) if File.exist?(@isopath)
      Sys.rm_rf(@isopath)
    end

    # Clean iso image
    if iso or deployments or all or isofull
      puts("Cleaning iso image...".colorize(:cyan))
      Dir[File.join(@imagepaths.first, '*.iso')].each{|x|
        puts("Deleting #{x}".colorize(:red))
        File.delete(x)
      }
    end

    # Clean vagrant vms that are no longer deployed
    if vms or all
      puts("Cleaning vagrant vms...".colorize(:cyan))
      if File.exist?(@vagrantpath)
        vgout = `#{@sudoinv}vagrant global-status --prune`.split("\n")
        puts(vgout)
        vms = vgout.select{|x| x.include?('virtualbox')}.map{|x| x.split(' ')[1]}
        Dir[File.join(@vagrantpath, '*')].map{|x| File.basename(x)}.each{|vm|
          if !vms.include?(vm)
            path = File.join(@vagrantpath, vm)
            puts("Removing vagrant env. for missing VM #{path}".colorize(:red))
            Sys.rm_rf(path)
          end
        }
      end
    end
  end

  # Build components as directed
  # @param profile [String] cyberlinux profile to build
  # @param initramfs [bool] build initramfs component
  # @param multiboot [bool] build multiboot component
  # @param deployments [Array] build given deployments
  # @param iso [bool] build iso image from whatever machine deployments exist
  # @param isofull [bool] build iso image including all machine deployments
  def build(profile, initramfs:nil, multiboot:nil, deployments:nil, iso:nil, isofull:nil)
    opts = [initramfs, multiboot, deployments, iso, isofull]
    !puts("Error: no build options specified".colorize(:red)) and exit unless opts.any?
    changed = false
    load_profile(profile)
    info
    create_dir_structure

    if opts.any?
      !puts("Error: must be executed as root".colorize(:red)) and
        exit unless Process.uid.zero?
      puts("#{'-' * 80}\nBuilding ISO components...\n#{'-' * 80}".colorize(:light_yellow))
    end

    # Build implicated deployments
    deployments = @profile[@k.deployments].keys if isofull
    deployments.each{|deployment| changed |= build_deployments(deployment)} if deployments

    # Build the build container for initramfs/multiboot
    changed |= build_deployments(@k.build) if not (deployments || []).include?(@k.build)

    # Build early userspace ramdisk for install executed by grub
    clean(initramfs:true) if changed
    changed |= build_initramfs_installer if [initramfs, iso, isofull, changed].any?

    # Build GRUB UI that boots initramfs installer and in turn the real kernel
    changed |= build_grub_multiboot if [multiboot, iso, isofull].any?

    # Create ISO Hybrid CD/USB bootable image
    # http://lukeluo.blogspot.co.uk/2013/06/grub-how-to-2-make-boot-able-iso-with.html
    @vars.isofile = File.join(@imagepaths.first,
      "#{@vars.distro.downcase}-#{profile}-#{@vars.release}-#{@vars.kernel}-#{@vars.arch}.iso")
    if [iso, isofull].any?
      puts("#{'-' * 80}\nBuilding ISO Hybrid CD/USB bootable image...\n#{'-' * 80}".colorize(:light_yellow))
      if changed or not File.exist?(@vars.isofile)
        cmd = "grub-mkrescue "
        
        # Set the volume label
        cmd += "-volid #{@vars.label} "

        # Create the ISO from @isopath
        cmd += "-o #{@vars.isofile} #{@isopath}"

        msg = "ISO Hybrid CD/USB bootable image:\n#{@vars.isofile}"
        if Sys.exec(cmd)
          puts("Successfully built #{msg}".colorize(:green))
        else
          !puts("Error: Failed to build #{msg}".colorize(:red)) and exit
        end
      end
    end
  end

  # Create the initramfs.img
  # which provides the boot environment we will install from
  # @returns true on changed
  def build_initramfs_installer
    create_dir_structure
    changed = false
    initramfs_digests = File.join(@initramfs_work, 'digests')
    initramfs_names = @profile[@k.deployments].select{|x| x[@k.type] == @k.machine}
      .map{|x| x[@k.deployment][@k.kernel]}.uniq.map{|x| "#{@initramfs_prefix}-#{x}"}

    puts("#{'-' * 80}\nBuilding initramfs images...\n#{'-' * 80}".colorize(:light_yellow))
    if syncfiles(File.basename(@initramfs_work), @initramfs_src, @initramfs_work, initramfs_digests) or
        not Dir[File.join(@initramfs_path, "#{@initramfs_prefix}*")].any?
      changed |= true
      installer = File.join(@initramfs_work, 'installer')
      installer_conf = File.join(@initramfs_work, 'installer.conf')
      mkinitcpio_conf = File.join(@initramfs_work, 'mkinitcpio.conf')

      # Resolve template
      Fedit.resolve(installer, @vars)

      # Build initramfs images in build container
      docker(@k.build, @k.build){|cont, home, cp, exec, execs, runuser|

        # Inject installer configuration
        cp.call("#{installer} #{cont}:/usr/lib/initcpio/hooks")
        cp.call("#{installer_conf} #{cont}:/usr/lib/initcpio/install/installer")
        cp.call("#{mkinitcpio_conf} #{cont}:/etc")
        #exec.call('bash -c "while :; do sleep 5; done"')

        # Build an initramfs for each installed kernel
        `#{execs} ls /lib/modules`.split(" ").compact.reject{|x| x.include?('extra')}.each{|kernel|
          name = "-" + kernel.split("-").last
          name = '' if name == "-ARCH"
          initramfs_name = initramfs_names.find{|x| x == "#{@initramfs_prefix}-linux#{name}"}
          puts("Creating #{initramfs_name}...".colorize(:cyan))
          puts("Using kernel: #{kernel}".colorize(:green))
          initramfs_image = File.join('/root', "#{initramfs_name}.img")

          exec.call("mkinitcpio -k #{kernel} -g #{initramfs_image}")
          cp.call("#{cont}:#{initramfs_image} #{@initramfs_path}")
          puts("Successfully built initramfs image #{@initramfs_path}/#{initramfs_name}.img".colorize(:green))
        }
      }
    end

    return changed
  end

  # Build bootable GRUB image with both BIOS and UEFI support
  # https://www.rodsbooks.com/efi-bootloaders/index.html
  # https://wiki.archlinux.org/index.php/Multiboot_USB_drive#Using_GRUB_and_loopback_devices
  # @returns true on changed
  def build_grub_multiboot
    create_dir_structure
    changed = false
    grub_digests = File.join(@grub_iso_work, 'digests')
    grub_iso_path = File.join(@grub_iso_work, 'boot/grub')
    kernels = @profile[@k.deployments].select{|x| x[@k.type] == @k.machine}
      .map{|x| x[@k.deployment][@k.kernel]}.compact.uniq.map{|x| "#{@kernel_prefix}-#{x}"}

    FileUtils.mkdir_p(grub_iso_path)
    puts("#{'-' * 80}\nBuilding grub multiboot...\n#{'-' * 80}".colorize(:light_yellow))
    if syncfiles(File.basename(@grub_iso_work), @grub_iso_src, grub_iso_path, grub_digests) or
        not Dir[File.join(@kernel_path, "#{@kernel_prefix}*")].any?
      changed |= true

      # Resolve templates
      Fedit.resolve(File.join(grub_iso_path, 'grub.cfg'), @vars)
      Fedit.resolve(File.join(grub_iso_path, "themes/#{@vars.distro}/theme.txt"), @vars)

      # Inject deploy entries from deployments
      motd = File.readlines(@motd_path)
      File.open(File.join(grub_iso_path, 'boot.cfg'), 'w'){|f|
        @profile[@k.deployments].select{|k,v| v[@k.type] == @k.machine}.reverse.each{|x|
          v = x.values.first
          kernel = "#{@kernel_prefix}-#{v[@k.install][@k.kernel]}"
          params = v[@k.install][@k.params] || ""
          params = "#{params} " if !params.empty?
          params += "kernel=#{v[@k.install][@k.kernel]}"
          deployments = @vars["#{x.keys.first}_deployments"]

          f << "    menuentry --class=deployment '#{v[@k.install][@k.entry]}' {\n"
          f << "        echo\necho\n"
          motd.each{|line| f << "        echo $\"          #{line.gsub("\n", "")}\"\n" }
          f << "        linux /boot/#{kernel} efi=$efi deployments=#{deployments} #{@vars.kernel_params} #{params if params}\n"
          f << "        initrd /boot/intel-ucode.img /boot/#{@initramfs_prefix}-#{v[@k.install][@k.kernel]}.img\n"
          f << "    }\n"
        }
      }
      Fedit.resolve(File.join(grub_iso_path, 'boot.cfg'), @vars)

      # Build grub components inside build container to ensure isolation
      docker(@k.build, 'root'){|cont, home, cp, exec, execs, runuser|

        # Extract GRUB boot files
        cp.call("#{cont}:/usr/share/grub/unicode.pf2 #{grub_iso_path}")

        # Extract memtest and intel-ucode as well as licenses
        cp.call("#{cont}:/boot/intel-ucode.img #{@ucode_image}.img")
        cp.call("#{cont}:/usr/share/licenses/intel-ucode/LICENSE #{@ucode_image}.LICENSE")
        cp.call("#{cont}:/boot/memtest86+/memtest.bin #{@memtest_image}")
        cp.call("#{cont}:/usr/share/licenses/common/GPL2/license.txt #{@memtest_image}.LICENSE")

        # Extract kernels
        kernels.each{|kernel|
          puts("Copying: ...to #{@kernel_path}/#{kernel}")
          cp.call("#{cont}:/boot/#{kernel} #{@kernel_path}")
        }
      }

      puts("Copying grub multiboot to destination...".colorize(:cyan))
      Dir.glob(File.join(@grub_iso_work, '**/*'), File::FNM_DOTMATCH).each{|x|
        if !['digests', 'efi.img'].any?{|y| y == File.basename(x)} and File.file?(x)
          dst = x.sub(@grub_iso_work, @isopath)
          puts("Copying: ...to #{dst}")
          FileUtils.mkdir_p(File.dirname(dst))
          FileUtils.cp(x, dst)
        end
      }

      puts("Successfully built grub multiboot".colorize(:green))
    end

    return changed
  end

  # Pack the given deployment or all deployments if no specific deployment given
  # @param deployments [list] deployments to pack into an image else all
  # @param disksize [int] disk size to use for pack
  # @param force [bool] pack even if already exists
  def pack(deployments, disksize:nil, force:nil)
    _deployments = @profile[@k.deployments].select{|x| x[@k.type] == @k.machine}
    deployments = deployments || _deployments.reject{|x| x[@k.name] == 'live'}
    puts("#{'-' * 80}\nPacking deployments #{deployments * ','}\n#{'-' * 80}".colorize(:light_yellow))
    !puts("Error: must be executed as non-root user".colorize(:red)) and
      exit unless not Process.uid.zero?
    create_dir_structure

    # Ensure we have the right binaries available
    !puts("Ensure 'packer' https://www.packer.io/downloads.html is in the path".colorize(:red)) and
      exit unless find_executable('packer')
    !puts("Please install 'virtualbox' via 'sudo pacman -S virtualbox'".colorize(:red)) and
      exit unless find_executable('vboxmanage')

    # Locate latest iso
    isos = getimages(@type.iso).keys
    !puts("Error: no ISOs found".colorize(:red)) and exit unless isos.any?
    @vars.isofile = isos.shift

    @vars.release = @vars.isofile[/-(.*?)-/, 1]
    puts("Release: #{@vars.release}".colorize(:cyan))
    puts("ISO: #{@vars.isofile}".colorize(:cyan))

    # Configure host-only network
    config_network = "#{@sudoinv}vboxmanage hostonlyif ipconfig "
    config_network += "#{@vars.netname} -ip #{@vars.netip} -netmask #{@vars.subnet}"
    if not Sys.exec(config_network, die:false)
      Sys.exec("#{@sudoinv}vboxmanage hostonlyif create")
      Sys.exec(config_network)
    end

    # Pack implicated deployments into vagrant boxes
    installables = _deployments.map{|x| x[@k.deployment][@k.entry]}.reverse.flatten.compact
    deployments.each do |deployment|

      # Remove old boxes and/or skip if current
      image = evalimages!(@type.box, deployment:deployment, force:force)
      !puts("Box #{image} already exists".colorize(:green)) and next if image

      # Clean up build artifacts and prep for build
      puts("Building vagrant image with packer for deployment '#{deployment}'".colorize(:cyan))
      output_dir = File.join(@packer_work, deployment)
      puts("Removing old packer artifacts at #{output_dir}".colorize(:red))
      rm_rf(output_dir)

      # Copy over and resolve packer template and scripts
      puts("Copy over and resolve packer template and scripts".colorize(:cyan))
      Dir.glob(File.join(@packer_src, '*.sh')).each{|x|
        FileUtils.cp(x, @packer_work)
        Fedit.resolve(File.join(@packer_work, File.basename(x)), @vars)
      }

      template = File.join(@packer_work, "#{deployment}.json")
      FileUtils.cp(File.join(@packer_src, 'packer.json'), template)
      @vars.deployment = deployment
      @vars.disksize = disksize || '40000'
      @vars.downs = ['"<down>"'] * installables.index(deployment) * ','
      Fedit.resolve(template, @vars)

      # Create a new vagrant image for the given deployment
      puts("Building vagrant image using packer".colorize(:cyan))
      pwd = Dir.pwd and Dir.chdir(@packer_work)
      Sys.exec("packer build -only=virtualbox-iso #{deployment}.json")
    end
  end

  # Deploy vagrant node/s
  # @param deployment [string] deployment to deploy
  # @param name [string] name to give the specific node/container being created
  # @param run [string] run the container with default run
  # @param exec [string] specific command to run in the container
  # @param nodes [list] list of node ids to deploy
  # @param ipv6 [bool] enable ipv6 on the node/s being deployed
  # @param vagrantfile [bool] export the vagrant file only
  # @param force [bool] deploy even if already exists
  def deploy(deployment, name:nil, run:nil, exec:nil, nodes:nil, ipv6:nil, vagrantfile:nil, force:nil)
    puts("#{'-' * 80}\nDeploying deployment '#{deployment}'\n#{'-' * 80}".colorize(:light_yellow))
    create_dir_structure
    deployment_yml = get_deployment_yml(deployment)

    # Deploy vagrant VM
    #---------------------------------------------------------------------------
    if deployment_yml[@k.type] == @k.machine
      uid, gid = Sys.drop_privileges

      # Check that vagrant is on the path and clean previously deployed VMs
      !puts("Ensure 'vagrant' https://www.vagrantup.com/downloads.html is in the path".colorize(:red)) and
        exit unless find_executable('vagrant')
      clean(vms:true)

      # Choose a vagrant box to use and update registry if needed
      vagrant_box = deployment
      box = getimages(@type.box, deployment:deployment).keys.shift
      if !box
        vagrant_box = "phR0ze/cyberlinux-#{deployment}"
        puts("Downloading '#{vagrant_box}' from vagrantup.com".colorize(:cyan))
      else
        !puts("Error: no box found for #{deployment}, please pack the box first".colorize(:red)) and exit unless box
        puts("Updating vagrant registry for '#{deployment}'".colorize(:cyan))
        Sys.exec("#{@sudoinv}vagrant box add #{deployment} #{box} --force")
      end

      # Configure host-only network
      !puts("Ensure 'virtualbox' https://www.virtualbox.org/wiki/Downloads is in the path".colorize(:red)) and
        exit unless find_executable('vboxmanage')
      config_network = "#{@sudoinv}vboxmanage hostonlyif ipconfig "
      config_network += "#{@vars.netname} -ip #{@vars.netip} -netmask #{@vars.subnet}"
      if not Sys.exec(config_network, die:false)
        Sys.exec("#{@sudoinv}vboxmanage hostonlyif create")
        Sys.exec(config_network)
      end

      # Generate vagrant node parameters
      #---------------------------------------------------------------------------
      profiles = []
      (nodes || [rand(2..254)]).each do |node|
        host = name || vagrant_box
        host = "#{host}#{node.to_s}".gsub(' ', '-').gsub('/', '-').gsub('_', '-')
        profile = {
          host: host,
          ip: "#{@vars.netip[0..-2]}#{node}/24",
          box: vagrant_box,
          cpus: deployment_yml[@k.vagrant][@k.cpus] || 1,
          ram: deployment_yml[@k.vagrant][@k.ram] || 512,
          vram: deployment_yml[@k.vagrant][@k.vram] || 8,
          net: @vars.netname,
          v3d: deployment_yml[@k.vagrant][@k.v3d] || @k.off,
          proxy: @proxyenv['http_proxy'],
          no_proxy: @proxyenv['no_proxy'],
          ipv6: ipv6
        }
        profiles << profile
        puts("Generating node: #{profile.to_s}".colorize(:cyan))
      end

      # Create Vagrantfile for deployment
      vagrantfile_path = File.join(@vagrantpath, 'Vagrantfile')
      FileUtils.cp(File.join(@packer_src, 'Vagrantfile'), vagrantfile_path)
      @vars.nodes = profiles.map{|x| '  ' + x.to_s} * ",\n"
      Fedit.resolve(vagrantfile_path, @vars)

      # Initialize a new vagrant instance
      #-----------------------------------------------------------------------
      if not vagrantfile
        puts("Initializing vagrant node from deployment '#{deployment}'".colorize(:cyan))
        vmpath = File.expand_path(FileUtils.mkdir_p(File.join(@vagrantpath, profiles.first[:host])).shift)
        FileUtils.cp(vagrantfile_path, vmpath)
        File.delete(vagrantfile_path)

        # Weird UI issue in that X apps can't open display :0 until reboot
        Dir.chdir(vmpath)
        Sys.exec("#{@sudoinv}vagrant up")
        Sys.exec("#{@sudoinv}vagrant reload")
      end

      Sys.raise_privileges(uid, gid)

    # Deploy docker container
    #---------------------------------------------------------------------------
    elsif deployment_yml[@k.type] == @k.container
      !puts("Error: must be executed as root".colorize(:red)) and
        exit unless Process.uid.zero?

      # Remove old 'live' images or skip if current
      image = evalimages!(@type.tgz, deployment:deployment, live:true, force:force)
      puts("Image #{image} already exists".colorize(:green)) if image

      # Load disk image if it exists
      if not image
        image = evalimages!(@type.tgz, deployment:deployment, live:false)
        image ? puts("Image #{image} exists importing".colorize(:green)) :
          !puts("Error: need to first build image '#{image}'".colorize(:red)) and exit
        Sys.exec("cat #{image} | docker import - #{File.basename(image, '.*')}:latest")
        image = File.basename(image, '.*')
      end

      # Run container
      #-------------------------------------------------------------------------
      if run or exec

        # Get docker params
        params = []
        deployments = get_deployments(deployment).reverse[0..-1].each{|x|
          docker = get_deployment_yml(x)[@k.docker]
          params << docker[@k.params] if docker[@k.params]
        }
        puts("docker: using params #{params}".colorize(:cyan))

        # Run docker container
        # Ex: docker run --rm --name dev66 -h dev66 -e TERM=xterm build-1.0.59 bash -c "while :; do sleep 5; done"
        cont = name || 'dev'
        env = '' and @proxyenv.each{|k,v| env << "-e #{k}=#{v} " if v}
        params = exec ? "-it #{env} #{image} #{exec}" :
          (params << "#{image} #{deployment_yml[@k.docker][@k.command]}").flatten * ' '
        begin
          Sys.exec("docker run --rm --name #{cont} --hostname #{cont} #{params}", die:false)
        ensure
          exists = `docker ps -a --format "{{.Names}}"`.split("\n").find{|x| x == cont}
          Sys.exec("docker kill #{cont}") if exists
        end
      end
    end
  end

  # Build the implicated deployments
  # @param target_deployment [string] specific deployment to build
  # @returns true if changed
  def build_deployments(target_deployment)
    changed = false
    !puts("Error: deployment '#{target_deployment}' doesn't exist".colorize(:red)) and
      exit unless target_deployment == @k.build || @profile[@k.deployments][target_deployment]
    # Build in reverse order to layer deployments
    deployments = get_deployments(target_deployment).reverse
    create_dir_structure

    deployments.each do |deployment|
      deployment_changed = false
      deployment_yml = get_deployment_yml(deployment)
      deployment_deps = get_deployments(deployment)[1..-1]
      deployment_work = FileUtils.mkdir_p(File.join(@deployments_work, deployment)).shift
      deployment_digests = File.join(deployment_work, 'digests')
      deployment_src = (deployment_yml[@k.source] || [deployment]).map{|x| File.join(@deployments_src, x)}
      deployment_image = deployment_yml[@k.type] == @k.machine ? File.join(@deployment_images_dst, "#{deployment}.sqfs") :
        File.join(@imagepaths.first, "#{deployment}-#{@vars.release}.tgz")
      puts("#{'-' * 80}\nBuilding deployment '#{deployment}'\n#{'-' * 80}".colorize(:light_yellow))

      begin
        # Mount all dependent deployments starting with base
        # Note: lowerdirs stacked from right to left (e.g. heavy, lite, base)
        if deployment_deps.any?
          puts("Mount deployment dependencies #{deployment_deps} for deployment '#{deployment}'".colorize(:cyan))
          Sys.exec("mount -t overlay -o lowerdir=%s,upperdir=%s,workdir=%s none %s" %
            [deployment_deps.map{|x| File.join(@deployments_work, x)} * ':', deployment_work, @tmp_dir, deployment_work])
        end

        # Install deployment specific packages via pacman
        deployment_changed |= installpkgs(deployment, deployment_yml, deployment_work)

        # Copy over all deployment data if it exists
        deployment_changed |= syncfiles(deployment, deployment_src, deployment_work, deployment_digests)

        # Apply configuration changes
        puts("Applying configs...".colorize(:cyan))
        changedfile = File.join(deployment_work, 'changed')
        if deployment_changed or not File.exist?(changedfile) or not File.exist?(deployment_image)
          vars = deployment_yml[@k.vars] ? @vars.to_h.merge(deployment_yml[@k.vars]) : @vars
          deployment_changed |= Config.apply(deployment_yml[@k.configs] || [],
            OpenStruct.new({root: deployment_work, vars: vars, configs: @profile[@k.configs]}))
          File.open(changedfile, 'w'){|f|}
        end

        # Build deployment image if needed
        if deployment_changed or not File.exist?(deployment_image)
          puts("Creating #{deployment_image}...".colorize(:cyan))
          Sys.umount(deployment_work, retries:10) if deployment_yml[@k.type] == @k.machine
          relocate_tracking_files(deployment_work)

          # Create squashfs image for machine deployments
          if deployment_yml[@k.type] == @k.machine
            Sys.exec("mksquashfs #{deployment_work} #{deployment_image} -noappend -comp xz -b 256K -Xbcj x86")
          else
            # Create compressed tarball for container deployments
            Sys.exec("tar --numeric-owner --xattrs --acls -C #{deployment_work} -czf #{deployment_image} .")
          end

          puts("Successfully built #{deployment_image}".colorize(:green))
          relocate_tracking_files(deployment_work, restore:true)
          deployment_changed |= true
        else
          puts("Image already built #{deployment_image}".colorize(:green))
        end

      ensure
        # Ensure joined file system is unmounted
        Sys.umount(deployment_work, retries:10)
        rm_rf(File.join(@tmp_dir, '*'))
      end
      changed |= deployment_changed
    end

    return changed
  end

  # Install packages for the given deployment
  # @param deployment [string] deployment name to work with
  # @param deployment_yml [yml] deployment yaml to work with
  # @param deployment_work [string] the directory where to install the deployment packages to
  # @returns true if any pkgs were installed else false
  def installpkgs(deployment, deployment_yml, deployment_work)
    msg = "Installing packages for '#{deployment}'..."
    pkgfile = File.join(deployment_work, 'packages')
    deployment_deps = get_deployments(deployment)[1..-1]

    # Handle packages differently based on type
    #---------------------------------------------------------------------------
    all_pkgs = getpkgs(deployment, deployment_yml)
    pkgs = {
      reg: all_pkgs.map{|x| x[@k.pkg] if !x[@k.ignore] and !x[@k.force]}.compact,
      force: all_pkgs.map{|x| x[@k.pkg] if x[@k.force]}.compact,
      ignore: all_pkgs.map{|x| x[@k.pkg] if x[@k.ignore]}.compact,
      conflict: all_pkgs.map{|x| "CONFLICT:#{x[@k.conflict]}" if x[@k.conflict]}.compact
    }

    # Filter out already installed packages
    #---------------------------------------------------------------------------
    if File.exist?(pkgfile)
      puts("Filtering out packages that are already installed".colorize(:cyan))
      installed_pkgs = nil
      File.open(pkgfile){|f| installed_pkgs = f.readlines.map{|x| x.strip}}
      [:reg, :conflict].each{|x| pkgs[x] = pkgs[x].select{|y| not installed_pkgs.include?(y)}}
    end

    # Install any missing packages
    #---------------------------------------------------------------------------
    if pkgs.any?{|k,v| v.any? if k != :conflict and k != :ignore}
      puts("#{msg}".colorize(:cyan))
      puts("Packages: #{pkgs[:reg]}")
      puts("Force Pkgs: #{pkgs[:force]}")
      puts("Ignore Pkgs: #{pkgs[:ignore]}")
      puts("Conflict Pkgs: #{pkgs[:conflict]}")

      # pacstrap replacement
      if pkgs[:conflict].any? or pkgs[:reg].any? or pkgs[:force].any?
        begin
          rm_rf(File.join(@pacman_path, 'pacman.log')) if !deployment_deps.any?

          # Prepare pacman for use
          if !File.exist?(@pacman_conf)
            Sys.exec("cp -a #{@pacman_src_conf} #{@pacman_path}")
            Sys.exec("cp -a #{@pacman_src_mirrors} #{@pacman_path}")
            Fedit.replace(@pacman_conf, /(Architecture = ).*/, "\\1#{@vars.arch}")
            # Leaave DBPath set as /var/lib/pacman and copy out sync
            Fedit.replace(@pacman_conf, /#(CacheDir\s+= ).*/, "\\1#{File.join(@pacman_path, 'cache')}")
            Fedit.replace(@pacman_conf, /#(LogFile\s+= ).*/, "\\1#{File.join(@pacman_path, 'pacman.log')}")
            Fedit.replace(@pacman_conf, /#(GPGDir\s+= ).*/, "\\1#{File.join(@pacman_path, 'gnupg')}")
            Fedit.replace(@pacman_conf, /#(HookDir\s+= ).*/, "\\1#{File.join(@pacman_path, 'hooks')}")
            Fedit.replace(@pacman_conf, /.*(\/.*mirrorlist).*/, "Include = #{@pacman_path}\\1")

            repos = Dir[File.join(@pacman_path, "*.mirrorlist")].map{|x| File.basename(x, '.mirrorlist')}
            Sys.exec("pacman-key --config #{@pacman_conf} --init")
            Sys.exec("pacman-key --config #{@pacman_conf} --populate #{repos * ' '}")
          end

          # Restore syncd databases for reuse to avoid constantly downloading them
          if Dir[File.join(@pacman_sync, "*")].any?
            FileUtils.mkdir_p(File.join(deployment_work, 'var/lib/pacman/sync'))
            Sys.exec("cp -a #{File.join(@pacman_sync, "*")} #{File.join(deployment_work, 'var/lib/pacman/sync')}")
          end

          # Remove these packages first
          if pkgs[:conflict].any?
            puts("Removing conflicting packages for '#{deployment}'...".colorize(:cyan))
            pkgs[:conflict].map{|x| x.split(':').last}.each{|conflict|
              !puts("Error: Failed to remove conflicting package".colorize(:red)) and
                exit unless Sys.exec("pacman -Rn -r #{deployment_work} -d -d --noconfirm #{conflict} &>/dev/null || true", die:false)
            }
          end

          # Install normal packages
          if pkgs[:reg].any?
            puts("Pacstrap package installs for '#{deployment}'...".colorize(:cyan))
            cmd = ['pacstrap', '-GMcd', deployment_work, '--config', @pacman_conf, '--needed', *pkgs[:reg]]
            cmd += ['--ignore', pkgs[:ignore] * ','] if pkgs[:ignore].any?
            !puts("Error: Failed to install packages correctly".colorize(:red)) and
              exit unless Sys.exec(cmd, env:@proxyenv)
          end

          # Install force packages
          if pkgs[:force].any?
            puts("Pacstrap package installs for '#{deployment}'...".colorize(:cyan))
            cmd = ['pacstrap', '-GMcd', deployment_work, '--config', @pacman_conf, '--needed', '--force', *pkgs[:force]]
            !puts("Error: Failed to install packages correctly".colorize(:red)) and
              exit unless Sys.exec(cmd, env:@proxyenv)
          end

          # Save off syncd databases for reuse to avoid constantly downloading them
          op = deployment_deps.any? ? "cp -a" : "mv"
          Sys.exec("#{op} #{File.join(deployment_work, 'var/lib/pacman/sync/*')} #{@pacman_sync}")
        ensure
          Sys.umount(File.join(deployment_work, 'dev'), retries: 10)
        end
      end

      # Update list of packages that were installed
      File.open(pkgfile, 'a'){|f| f.puts(pkgs[:reg])}
    else
      puts("#{msg}skipping".colorize(:cyan))
    end

    return pkgs.any?{|k,v| v.any? if k != :conflict and k != :ignore }
  end

  # Get packages for the given deployment
  # @param deployment [string] deployment name
  # @param deployment_yml [yml] deployment yaml to work with
  # @returns list of packages for the given deployment
  def getpkgs(deployment, deployment_yml)
    result = []

    # Detect multilib value
    multilib = deployment_yml[@k.multilib] || false
    puts("Multilib: #{multilib} for deployment '#{deployment}'".colorize(:cyan))

    # Get all packages for given app
    resolve_app = ->(app, pkgs){

      # Lookup app reference
      if app.is_a?(String)
        _app = @profile[@k.apps][app]
        !puts("Error: invalid app reference '#{app}'".colorize(:red)) and exit unless _app
        _app.each{|x| resolve_app.call(x, pkgs) }

      # Only pull out pkgs from app
      elsif app[@k.install]
        pkgs << app[@k.install]
      end

#      return pkgs.map{|x|
#        if x[@k.install] || (x[@k.ignore] && !x[@k.pkg])
#          pkgkey = x[@k.install] || x[@k.ignore]
#          pkgset = @profile[@k.packages][pkgkey].clone
#          !puts("Error: missing package set '#{pkgkey}'".colorize(:red)) and exit unless pkgset
#          # TODO: when multilib=true and arch is i686 then do opposite
#          pkgset.reject!{|y| multilib ? y[@k.multilib] == false : y[@k.multilib]} if x[@k.install]
#          pkgset.each{|y| y[@k.ignore] = true } if x[@k.ignore]
#          pkgset
#        else
#          x
#        end
#      }.flatten}
    }
    deployment_yml[@k.apps].each{|x| resolve_app.call(x, result) }

    return result.uniq
  end

  # Spins up indicated container and executes the given block
  # in the container then terminates the container.
  # @param deployment [string] container to use
  # @param user [string] user to work with
  # @param block [block] block of code to execute
  def docker(deployment, user, &block)

    # Spin up given container and wait for it to be ready
    #---------------------------------------------------------------------------
    cont = "dev#{rand(10..99)}"
    thread = Thread.new{deploy(deployment, name:cont, run:true)}
    (1..100).each{|i|
      if not `docker ps`.include?(cont)
        puts("Waiting for container '#{cont}' to be ready...") if i % 2 == 0
        sleep(1)
      else
        break
      end
    }

    # Execute in container
    #---------------------------------------------------------------------------
    vars = '' and @proxyenv.each{|k,v| vars << "export #{k}=#{v} && " if v}
    home = user == 'root' ? "/root" : "/home/#{user}"
    cp = ->(cmd){Sys.exec("docker cp #{cmd}")}
    exec = ->(cmd){Sys.exec("docker exec #{cont} bash -c \"#{vars}#{cmd.gsub(/"/, '\"')}\"")}
    execs = "docker exec #{cont}"
    runuser = ->(cmd){Sys.exec("docker exec #{cont} runuser #{user} -c \"#{vars}#{cmd.gsub(/"/, '\"')}\"")}
    block.call(cont, home, cp, exec, execs, runuser)

    # Shutdown container
    #---------------------------------------------------------------------------
    thread.kill
    thread.join
  end

  # Syncs the source and work directories for a given deployment
  # @param deployment [string] deployment to work with
  # @param deployment_src [path or paths] deployment source directories to work with
  # @param deployment_work [path] deployment work directory to work with
  # @param deployment_digests [path] deployment digests file
  # @param block [block] block of code to execute
  def syncfiles(deployment, deployment_src, deployment_work, deployment_digests, &block)
    changed = false
    deployment_src = [deployment_src] if deployment_src.is_a?(String)
    return changed if !deployment_src.any?{|x| File.exist?(x)}

    msg = "Syncing from #{deployment_src}"
    sources = deployment_src.select{|x| File.exist?(x)}
    reversed = sources.sort.reverse
    files = sources.map{|src| Dir.glob(File.join(src, '**/*'), File::FNM_DOTMATCH).reject{|x| File.directory?(x)}}.flatten
    newfiles, modifiedfiles, deletedfiles = Fedit.digests_changed(deployment, deployment_digests, files)
    if newfiles.any? or modifiedfiles.any? or deletedfiles.any? or not File.exist?(deployment_digests)
      changed |= true
      puts(msg.colorize(:cyan))

      # Remove files that no longer exist from work dir not data dir
      deletedfiles.each{|x|
        mask = reversed.find{|y| x.include?(y)}
        target = File.join(deployment_work, x.split(mask).last)
        puts("Deleting #{target}".colorize(:red))
        File.delete(target)
      }

      # Copy over files from data dir to work dir
      files.each{|x|
        mask = reversed.find{|y| x.include?(y)}
        target = File.join(deployment_work, x.split(mask).last)
        puts("Copying: #{x} => #{target}")
        FileUtils.mkdir_p(File.dirname(target))
        FileUtils.cp(x, target)
      }

      # Copy user files to root as well
      files.select{|x| x.include?("etc/skel")}.each{|x|
        mask = reversed.find{|y| x.include?(y)}
        target = File.join(deployment_work, x.split(mask).last)
        puts("Copying: #{x} => #{target.sub('etc/skel', 'root')}")
        FileUtils.mkdir_p(File.dirname(target.sub('etc/skel', 'root')))
        FileUtils.cp(x, target.sub('etc/skel', 'root'))
      }

      # Execute block
      block.call if block

      # Update digests
      Fedit.update_digests(deployment, deployment_digests, files)
    else
      puts("#{msg}...skipping".colorize(:cyan))
    end

    puts("Completed constructing/modifiying files for '#{deployment}' deployment".colorize(:green))

    return changed
  end

  # Evaluate images matching type and deployment; removing if stale
  # @param type [string] image type to get
  # @param deployment [string] deployment to get image for or all
  # @param live [bool] evaluate live(true) vs disk(false)
  # @param force [bool] remove images matching conditions
  # @returns image matching the version
  def evalimages!(type, deployment:nil, live:nil, force:nil)
    image_exists = nil
    curver = @vars.release.split('.').map{|x| x.to_i}

    getimages(type, deployment:deployment, live:live).keys.each{|image|
      puts("Evaluating '#{live ? 'live' : 'disk'}' image #{image}".colorize(:cyan))
      name = live ? image[/-(.*)/, 1] : image[/-(.*?)\.#{type}/, 1]
      imagever = name.split('.').map{|x| x.to_i}
      if force or (imagever <=> curver) == -1
        puts("Removing image '#{live ? 'live' : 'disk'}' #{image} - #{force ? 'forced' : 'outdated'}".colorize(:red))
        if not live
          File.delete(image)
        elsif type == @type.tgz

          # Remove any old containers that depend on that image
          cntrs = `sudo docker ps -a --format "{{.Image}}:{{.ID}}"`.split("\n")
            .select{|x| x.start_with?(image)}
          cntrs.each{|x| Sys.exec("sudo docker rm #{x.split(':')[1]}")}

          # Remove image
          Sys.exec("sudo docker rmi #{image} --force")
        end
      else
        image_exists = image
      end
    }

    return image_exists
  end

  # Get all images sorted newest to oldest
  # @param type [string] image type to get
  # @param deployment [string] deployment to get image for or all
  # @param live [bool] get live(true) vs disk(false)
  # @param die [bool] die on error
  # @returns all images sorted by version and optionally filtered by deployment
  def getimages(type, deployment:nil, live:nil, die:false)
    image_maps = {}

    # Get deployed image data
    #---------------------------------------------------------------------------
    if live and type == @type.tgz
      images = {}
      `sudo docker images --format "{{.Repository}}:{{.Size}}"`.split("\n")
        .select{|x| deployment ? x.start_with?("#{deployment}-") : true }
        .map{|x| x.split(':')}.each{|x| images[x.first] = x.last}
      images.keys.sort_by{|x| (x[/-(\d+\.\d+\.\d+).*/, 1] || "<none>.").split('.').map{|y| y.to_i} }
        .reverse!.each{|x| image_maps[x] = images[x]}

    # Get disk image data
    #---------------------------------------------------------------------------
    elsif not live

      # Get all files of the given type from the watched locations
      files = []
      files += @imagepaths.map{|x| File.exist?(x) ? Dir[File.join(x, "*.#{type}")] : []}.flatten

      # For isos and boxes filter on files that contain the distro name
      if [@type.box, @type.iso].include?(type)
        files.delete_if{|x| !File.basename(x).start_with?(@vars.distro)}
      end

      # Sort the resulting list by version
      images = deployment ? files.select{|x| x.include?(deployment)} : files
      images = [@type.sqfs, @type.img].include?(type) ? images.sort :
        images.sort_by{|x| x[/-(\d+\.\d+\.\d+).*/, 1].split('.').map{|y| y.to_i}}.reverse

      # Add file size to each entry
      images.each{|x| image_maps[x] = File.size(x)}
    end

    # Print result for single search
    if deployment and image_maps.keys.first
      puts("Located '#{live ? 'live' : 'disk'}' image #{image_maps.keys.first}".colorize(:cyan))
    elsif deployment and die
      !puts("Could not find image type '#{type}' for '#{deployment}'".colorize(:red)) and exit
    end

    return image_maps
  end

  # Relocate the tracking files
  # @param deployment_work [path] directory to get tracking files from
  # @param restore [bool] move the relocated files back to their original location
  # @returns image matching the version
  def relocate_tracking_files(deployment_work, restore:false)
    digests = File.join(deployment_work, 'digests')
    packages = File.join(deployment_work, 'packages')
    changed = File.join(deployment_work, 'changed')
    if not restore
      FileUtils.mv(digests, @tmp_dir) if File.exist?(digests)
      FileUtils.mv(packages, @tmp_dir) if File.exist?(packages)
      FileUtils.mv(changed, @tmp_dir) if File.exist?(changed)
    end

    _digests = File.join(@tmp_dir, File.basename(digests))
    _packages = File.join(@tmp_dir, File.basename(packages))
    _changed = File.join(@tmp_dir, File.basename(changed))
    if restore
      FileUtils.mv(_digests, deployment_work) if File.exist?(_digests)
      FileUtils.mv(_packages, deployment_work) if File.exist?(_packages)
      FileUtils.mv(_changed, deployment_work) if File.exist?(_changed)
    end
  end

  # Get deployment dependencies
  # @param deployment [string] the deployment to get dependencies for
  # @returns list of deployments (e.g. heavy => heavy, lite, shell, base)
  def get_deployments(deployment)
    deployments = [deployment]
    return deployments if deployment == @k.build
    !puts("Error: invalid deployment '#{deployment}'".colorize(:red)) and
      exit if not @profile[@k.deployments][deployment]

    _deployment = deployment
    while _deployment
      _deployment = @profile[@k.deployments][_deployment][@k.base]
      deployments << _deployment if _deployment
    end

    return deployments
  end

  # Get deployment yaml by name and resolve templating
  # @param deployment [string] deployment name to get yaml for
  # @returns yaml for the indicated deployment
  def get_deployment_yml(deployment)
    yml = deployment == @k.build ? @profile[@k.build] : @profile[@k.deployments][deployment]
    !puts("Error: invalid deployment '#{deployment}'".colorize(:red)) and exit if not yml

    # Resolve templating for the given deployment
    vars = yml[@k.vars] ? @vars.to_h.merge(yml[@k.vars]) : @vars
    yml = yml.erb(vars)

    return yml
  end

end

#-------------------------------------------------------------------------------
# Main entry point
#-------------------------------------------------------------------------------
if __FILE__ == $0
  app = 'reduce'
  reduce = Reduce.new
  version = reduce.instance_variable_get(:@vars).release
  examples = "Examples:\n".colorize(:green)
  examples += "Full ISO Build: sudo ./#{app} clean build --iso-full --profile=personal\n".colorize(:green)
  examples += "Rebuild initramfs: sudo ./#{app} clean build --initramfs --iso --profile=personal\n".colorize(:green)
  examples += "Rebuild multiboot: sudo ./#{app} clean build --multiboot --iso --profile=personal\n".colorize(:green)
  examples += "Clean pacman dbs: sudo ./#{app} clean --pacman\n".colorize(:green)
  examples += "Build k8snode deployment: sudo ./#{app} clean build --deployments=k8snode --iso --profile=personal\n".colorize(:green)
  examples += "Pack k8snode deployment: ./#{app} pack --deployments=k8snode\n".colorize(:green)
  examples += "Deploy nodes: sudo ./#{app} deploy --deployment=k8snode --nodes=10,11,12\n".colorize(:green)
  examples += "Deploy container: sudo ./#{app} deploy --run --deployment=build\n".colorize(:green)
  examples += "\n"

  opts = Cmds.new(app, version, examples)
  opts.add('info', 'List build info', [])
  opts.add('list', 'List out components', [
    CmdOpt.new('--all', 'List all components'),
    CmdOpt.new('--boxes', 'List all boxes'),
    CmdOpt.new('--isos', 'List all isos'),
    CmdOpt.new('--images', 'List all docker images'),
    CmdOpt.new('--raw', 'Automation suitable output'),
  ])
  opts.add('clean', 'Clean ISO components', [
    CmdOpt.new('--all', 'Clean all components'),
    CmdOpt.new('--pacman', 'Clean pacman repos'),
    CmdOpt.new('--pacman-all', 'Clean pacman repos and cache'),
    CmdOpt.new('--initramfs', 'Clean initramfs image'),
    CmdOpt.new('--multiboot', 'Clean grub multiboot'),
    CmdOpt.new('--deployments=x,y,z', 'Clean given deployments', type:Array),
    CmdOpt.new('--iso', 'Clean bootable ISO'),
    CmdOpt.new('--iso-full', 'Clean bootable ISO and all machine deployments'),
    CmdOpt.new('--vms', 'Clean VMs that are no longer deployed'),
  ])
  opts.add('build', 'Build ISO components', [
    CmdOpt.new('--profile=PROFILE', 'Build from the given profile', type:String, required:true),
    CmdOpt.new('--initramfs', 'Build initramfs image'),
    CmdOpt.new('--multiboot', 'Build grub multiboot'),
    CmdOpt.new('--deployments=x,y,z', 'Build given deployments', type:Array),
    CmdOpt.new('--iso', 'Build USB bootable ISO with existing deployments'),
    CmdOpt.new('--iso-full', 'Build USB bootable ISO with all machine deployments')
  ])
  opts.add('pack', 'Pack ISO deployments into vagrant boxes', [
    CmdOpt.new('--all', 'Pack all deployments'),
    CmdOpt.new('--deployments=x,y,z', 'Pack given deployments', type:Array),
    CmdOpt.new('--disksize=DISKSIZE', 'Set the disk size in MB e.g. 10000', type:String),
    CmdOpt.new('--force', 'Pack the given deployment/s even if they already exists'),
  ])
  opts.add('deploy', 'Deploy VMs or containers', [
    CmdOpt.new('--deployment=DEPLOYMENT', 'Deploy a specific deployment VM', type:String, required:true),
    CmdOpt.new('--name=NAME', 'Give a name to the specific node being deployed', type:String),
    CmdOpt.new('--run', 'Run default container run'),
    CmdOpt.new('--exec=CMD', 'Specific command to run in container', type:String),
    CmdOpt.new('--nodes=x,y,z', 'Comma delimited list of last octet IPs (e.g. 10,11,2)', type:Array),
    CmdOpt.new('--force', 'Deploy the given deployment/s even if already exists'),
    CmdOpt.new('--ipv6', 'Enable ipv6 on the given nodes'),
    CmdOpt.new('--vagrantfile', 'Export the Vagrantfile only'),
  ])
  opts.parse!

  # Execute
  puts(opts.banner) unless opts[:raw]

  # Execute 'info' command
  reduce.info if opts[:info]

  # Execute 'list' command
  reduce.list(boxes: opts[:boxes], isos: opts[:isos], images: opts[:images], all: opts[:all]) if opts[:list]

  # Execute 'clean' command
  reduce.clean(pacman: opts[:pacman], pacman_all: opts[:pacman_all], initramfs: opts[:initramfs],
    multiboot: opts[:multiboot], deployments: opts[:deployments], iso: opts[:iso], vms: opts[:vms], all: opts[:all],
    isofull: opts[:isofull]) if opts[:clean]

  # Execute 'build' command
  reduce.build(opts[:profile], initramfs: opts[:initramfs], multiboot: opts[:multiboot],
    deployments: opts[:deployments], iso: opts[:iso], isofull: opts[:isofull]) if opts[:build]

  # Execute 'pack' command
  reduce.pack(opts[:deployments], disksize: opts[:disksize], force: opts[:force]) if opts[:pack]

  # Execute 'deploy' command
  reduce.deploy(opts[:deployment], name: opts[:name], run: opts[:run], exec: opts[:exec], nodes: opts[:nodes],
    ipv6: opts[:ipv6], vagrantfile: opts[:vagrantfile], force: opts[:force]) if opts[:deploy]
end

# vim: ft=ruby:ts=2:sw=2:sts=2
